"""empty message

Revision ID: e5faa8b8ebb1
Revises: 8bfddbd3a6d7
Create Date: 2020-12-29 14:58:19.064174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5faa8b8ebb1'
down_revision = '8bfddbd3a6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###
