"""first migrate

Revision ID: e6f7bd918b6a
Revises: 
Create Date: 2020-11-04 21:38:25.334496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f7bd918b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinkList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=64), nullable=True),
    sa.Column('jancode', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinkList_productName'), 'drinkList', ['productName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drinkList_productName'), table_name='drinkList')
    op.drop_table('drinkList')
    # ### end Alembic commands ###
